export interface Event {
  id?: number; // Optional: This will be auto-generated by the backend when creating the event
  title: string; // The title of the event
  description: string; // The description of the event
  date: string; // The date of the event, typically in ISO string format
  location: string; // The location of the event
}
